name: 'Build and Test'
description: 'Do a npm build and teat'

runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash
    - run: npm run test -- --headless
      shell: bash
    - run: npm run build
      shell: bash
