name: "Build and Test"
description: "Do a npm build and teat"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm ci
      shell: bash
    - run: npm run test -- --watch=false --browsers=ChromeHeadless
      shell: bash
    - run: npm run build
      shell: bash
