name: "Check Tags"
description: "Check git tag and npm version for a repository to prevent wrong publications."
inputs:
  npmPackageName: # id of input
    description: "The npm package to get the latest version from the npm registry."
    required: false
    default: "@dlr-eoc/core-ui"
  packagePath:
    description: "The path to the package.json in the repository."
    required: false
    default: "./package.json"

runs:
  using: "composite"
  steps:
    - run: git fetch --prune --all --unshallow --tags
      shell: bash

      #       testPackage='testPackage'
      #       latestNpmVerion=$(npm show "$testPackage" version)
      # Check if the latest git Tag is the same as the repo npm version
      # Check if the repo npm version is higher the the latest version on npm
    - run: |
        path="${GITHUB_ACTION_PATH/.\//''}"
        echo "$path"
        echo "$INPUT_PACKAGEPATH"
        echo "$INPUT_NPMPACKAGENAME"

        latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
        reqVersion="require('${{ inputs.packagePath }}').version"
        packageVersion=$(node -p $reqVersion)

        latestNpmVerion=0.1.0

        if [ "${latestTag:1}" == "$packageVersion" ] && [ "$packageVersion"  != "$latestNpmVerion" ]
        then
          echo "Tag:${latestTag} - repo:${packageVersion} - npm:${latestNpmVerion}"
        else
          echo "Tag:${latestTag} - repo:${packageVersion} - npm:${latestNpmVerion}"
        fi

      shell: bash
