# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev Test

on:
  push:
    branches-ignore:
      # run on all branches other then main
      - main
    tags-ignore:
      # And do not run for any tags
      - '*'

jobs:
  event:
    runs-on: ubuntu-latest
    steps:
    - run: |
          echo "${{ github.event_name }}"
          echo "${{ github.ref }}"
