# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev Test

on:
  push:
    branches-ignore:
      # run on all branches other then main
      - main
    tags-ignore:
      # And do not run for any tags
      - "*"
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # check out before using actions reference from the same repository!
      - uses: actions/checkout@v2
      - uses: ./.github/actions/check-tags

  dev:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/check-tags
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: ./.github/actions/build-test
      - name: Archive dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "dist"
          path: dist
