# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev Test

on:
  push:
    branches-ignore:
      # run on all branches other then main
      - main
    tags-ignore:
      # And do not run for any tags
      - "*"
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/check-tags
