# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev Test

on:
  push:
    branches-ignore:
      # run on all branches other then main
      - main
    tags-ignore:
      # And do not run for any tags
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: ./.github/actions/test
      - uses: ./.github/actions/build
      - name: Archive dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "dist"
          path: dist
