name: Build and Deploy pages
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build # This example project is built using npm and outputs the result to the 'dist' folder.
        run: |
          npm ci
          npx ng build --project=test-app --base-href=/github-actions-test/

      # https://docs.github.com/de/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow
      # use this and not upload-artifact@v4 because so all metadata is set correctly
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'dist'

      - name: Deploy
        uses: actions/deploy-pages@v4