name: Build and Deploy pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build # This example project is built using npm and outputs the result to the 'dist' folder.
        run: |
          npm ci
          npx ng build test-app  --prod --aot --vendor-chunk --common-chunk --delete-output-path --build-optimizer --base-href=/github-actions-test/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/test-app # The folder the action should deploy.
