name: GitHub Script Test
on:
  push:
    branches:
      - main

jobs:
  testscript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install
        run: npm ci

      - name: Github script
        uses: actions/github-script@v4
        id: set-result
        with:
          script: |
            const fetch = require('cross-fetch')
            const response = await fetch('https://jsonplaceholder.typicode.com/todos/1');
            const todo = await response.json();
            return todo;

      - name: Get result
        run: echo "${{steps.set-result.outputs.result.title }}"
