name: Main Release
on:
  push:
    branches: [ main ]
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
  event:
    runs-on: ubuntu-latest
    steps:
    - run: |
          echo "${{ github.event_name }}"
          echo "${{ github.ref }}"
