name: Main Release
on:
  push:
    branches: [main]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run test"
          echo "${{ github.event_name }}"
          echo "${{ github.ref }}"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run build"

  pre-publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run pre-publish"

  publish-gpr:
    needs: pre-publish
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run publish-gpr"

  publish-npm:
    needs: pre-publish
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run publish-npm"
