name: Main Release

# TODO: check run this workflow only if a certain tag exists and there is no npm version for it published
# git tag -l v0.3.0
# https://github.com/marketplace/actions/github-tag-check
on:
  pull_request:
    types: [closed]
    branches:
    - main

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run test"
          echo "${{ github.event_name }}"
          echo "${{ github.ref }}"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run build"

  pre-publish:
    needs: build
#    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run pre-publish"

  publish-gpr:
    needs: pre-publish
#    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run publish-gpr"

  publish-npm:
    needs: pre-publish
#    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run publish-npm"
