name: Node.js CI Package

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
    branches: [main]
  push:
    tags:
      - '*'


jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/download-artifact@v2
    - name: Download dist result from job build
      with:
        name: "dist"
        path: dist
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd ./dist && ls -la
