name: On workflow dispatch Var Test

on:
  push:
  workflow_dispatch:
    inputs:
      testInput1:
        description: "test input"
        required: false

env:
  testVar2: 2

jobs:
  logevent1:
    runs-on: ubuntu-latest
    steps:
      - name: log input and vars
        run: |
          echo "github.testInput1: ${{ github.testInput1 }}"
          echo "github.event.inputs.testInput1: ${{ github.event.inputs.testInput1 }}"
          echo "github.env.testVar2: ${{ github.env.testVar2 }}"
          echo "env.testVar2: ${{ env.testVar2 }}"

  logevent2:
    needs: logevent1
    runs-on: ubuntu-latest
    steps:
      - name: log vars
        uses: actions/github-script@v5
        id: log-vars
        with:
          script: |
            core.setOutput('testOutput', 'ffff');
            core.exportVariable('testVersion', '1.0.1');
            process.env.testVersion = '1.0.1';
            process.env.testVar2 = 20;
            return 'xyz';

  logevent3:
    needs: logevent2
    runs-on: ubuntu-latest
    steps:
      - name: log vars github-script
        uses: actions/github-script@v5
        id: log-vars
        with:
          script: |
            if(process.env){
              console.log('process.env.testVar2: ',process.env.testVar2);
              console.log('process.env.testVersion: ',process.env.testVersion);
            }else{
              console.log('no process.env');
            }

            if(github.env){
              console.log('github.env.testVar2: ',github.env.testVar2);
            }else{
              console.log('no github.env');
            }

            if(github.event){
              console.log('github.event.inputs.testInput1: ',github.event.inputs.testInput1);
            }else{
              console.log('no github.event');
            }

            if(needs){
              console.log('needs.logevent2.outputs.testOutput: ',needs.logevent2.outputs.testOutput);
            }else{
              console.log('no needs');
            }


      - name: log vars shell
        run: |
          echo ": needs.logevent2.outputs.testOutput: ${{ needs.logevent2.outputs.testOutput }}"
          echo "needs.logevent2.outputs.TESTOUTPUT: ${{ needs.logevent2.outputs.TESTOUTPUT }}"
          echo "needs.logevent2.outputs.TEST_OUTPUT : ${{ needs.logevent2.outputs.TEST_OUTPUT }}"
          echo ": github.env.testVar2: ${{ github.env.testVar2 }}"
          echo "${{ env.VERSION_TAG }}"
