name: On workflow dispatch

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]"
  workflow_dispatch:
    inputs:
      ref:
        description: 'github.ref'
        required: false

jobs:
  logevent1:
    if: ${{ github.event.inputs.ref }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ github.ref }}"
        echo "${{ github.event.inputs.ref }}"
        echo "${{ toJSON(github.event) }}!"
  logevent2:
    if: ${{ !github.event.inputs }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ github.event_name }}"
        echo "${{ github.ref }}"
        echo "${{ toJSON(github.event) }}!"
  # Test create Release on tag push https://github.com/softprops/action-gh-release
  gh-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
