name: On workflow dispatch Var Test

on:
  push:
  workflow_dispatch:
    inputs:
      testInput1:
        description: "test input"
        required: false

env:
  testVar2: 2

jobs:
  setOutputs:
    runs-on: ubuntu-latest
    steps:
      - name: Set output shell
        id: testOutput1
        run: echo '::set-output name=testOutputName1::ffff1'

      - name: Set output github-script
        uses: actions/github-script@v5
        id: testOutput2
        with:
          script: |
            core.setOutput('testOutputName2', 'ffff2');

      - name: Return output github-script
        uses: actions/github-script@v5
        id: testOutput3
        with:
          script: |
            return 'ffff3';
    outputs:
      testOutput1: ${{ steps.testOutput1.testOutputName1 }}
      testOutput2: ${{ steps.testOutput2.testOutputName2 }}
      testOutput3: ${{ steps.testOutput3.result }}
      testOutput4: "ffff4"

  setVars:
    runs-on: ubuntu-latest
    env:
      TEST_VAR_3: "aaaa3"
    steps:
      - name: Set Var shell
        run: echo "TEST_VAR_1=aaaa1" >> $GITHUB_ENV

      - name: Set Var github-script
        uses: actions/github-script@v5
        with:
          script: |
            core.exportVariable('TEST_VAR_2', 'aaaa2');

  logevent2:
    runs-on: ubuntu-latest
    needs: setOutputs
    steps:
      - name: log vars shell
        run: |
          echo "needs.setOutputs.outputs.testOutput1: ${{ needs.setOutputs.outputs.testOutput1 }}"
          echo "needs.setOutputs.outputs.testOutput2: ${{ needs.setOutputs.outputs.testOutput2 }}"
          echo "needs.setOutputs.outputs.testOutput3: ${{ needs.setOutputs.outputs.testOutput3 }}"
          echo "needs.setOutputs.outputs.testOutput4: ${{ needs.setOutputs.outputs.testOutput4 }}"
          echo "github.event.inputs.testInput1: ${{ github.event.inputs.testInput1 }}"

          echo "-----------------------------------------"

          echo "${{ toJSON(needs) }}"

      - name: log vars github-script
        uses: actions/github-script@v5
        with:
          script: |
            if(github.env){
              console.log('github.env);
            }else{
              console.log('no github.env');
            }

            if(github.event){
              console.log('github.event);
            }else{
              console.log('no github.event');
            }

            console.log('---------------------------------');
            console.log(process.env);
