name: On pull request - from branch release-...

# TODO: check run this workflow only if a certain tag exists and there is no npm version for it published
# git tag -l v0.3.0
# https://github.com/marketplace/actions/github-tag-check
on:
  pull_request:
    branches:
      - main

jobs:
  checkCommits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # needs uses: actions/checkout@ is script is required
      - name: Github script
        uses: actions/github-script@v5
        id: get-tag2
        with:
          script: |
            const script = require('./.github/github-scripts/checkPrHasTag.js');
            await script({ github, context, core, exec, require });
        # is the latest tag always the version we want to build???
