name: Filter Tags
on:
  push:
    branches-ignore:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-next.[0-9]+"

jobs:
  event:
    # skip job if rrf is not tags and includes next
    if: startsWith(github.ref, 'refs/tags') && contains(github.ref, '-next')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event_name }}"
          echo "${{ github.ref }}"
          echo "${{ github.ref }}"
