name: Pre Release
on:
  push:
    branches-ignore:
      - "*"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-next.[0-9]+"

jobs:
  checkTagOnNpm:
    runs-on: ubuntu-latest
    steps:
      # check out before using actions reference from the same repository!
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: rm -f .npmrc
      - uses: ./.github/actions/check-tag-on-npm
        with:
          npmPackageTags: "v0.4.0-next.1 , v0.4.0-next.2 , v0.9.0, v1.0.0, v1.0.1, v1.0.2, v1.0.3"
          tag: "${{ github.ref }}"

  test:
    needs: checkTagOnNpm
    runs-on: ubuntu-latest
    steps:
      # check out before using actions reference from the same repository!
      - uses: actions/checkout@v4
      - run: |
          echo "run test"
          echo "${{ github.event_name }}"
          echo "${{ github.ref }}"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # check out before using actions reference from the same repository!
      - uses: actions/checkout@v4
      - run: |
          echo "run build"

  pre-publish:
    needs: build
    #    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run pre-publish"

  publish-gpr:
    needs: pre-publish
    #    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run publish-gpr"

  publish-npm:
    needs: pre-publish
    #    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run publish-npm"

  # Test create Release on tag push https://github.com/softprops/action-gh-release
  gh-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
