name: Pre Release
on:
  push:
    branches-ignore:
      - "*"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-next.[0-9]+"

jobs:
  checkTags:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      # check out before using actions reference from the same repository!
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: rm -f .npmrc
      - uses: ./.github/actions/check-tags
        with:
          npmPackageName: "@dlr-eoc/core-ui"

  test:
    needs: checkTags
    runs-on: ubuntu-latest
    steps:
      # check out before using actions reference from the same repository!
      - uses: actions/checkout@v2
      - run: |
          echo "run test"
          echo "${{ github.event_name }}"
          echo "${{ github.ref }}"

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # check out before using actions reference from the same repository!
      - uses: actions/checkout@v2
      - run: |
          echo "run build"

  pre-publish:
    needs: build
    #    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run pre-publish"

  publish-gpr:
    needs: pre-publish
    #    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run publish-gpr"

  publish-npm:
    needs: pre-publish
    #    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "run publish-npm"
