# lint workflows: https://rhysd.github.io/actionlint/
name: GitHub Packages Test
on:
  push:
    branches-ignore:
      - "*"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-next.[0-9]+"

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6
        - uses: actions/setup-node@v6
          with:
            node-version: 24
        - run: rm -f .npmrc
        - run: npm ci
        - run: npm run build:all
        - run: |
              for dir in ./dist/*/
              do
                  dir=${dir%*/}
                  ls "$dir" -la
              done
          # https://docs.github.com/de/actions/writing-workflows/choosing-what-your-workflow-does/storing-and-sharing-data-from-a-workflow
        - name: Archive dist artifacts
          uses: actions/upload-artifact@v4
          with:
            name: "dist"
            path: dist

  publish-gpr:
    # build artifact can not be used from old workflow?
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Download dist result from job build
        uses: actions/download-artifact@v4
        with:
          name: "dist"
          path: dist
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com/
          scope: "@boeckmt"
      - run: npm ci
      - run: node -v
      - run: npm -v
      # npm publish "$dir" --access public --tag "next" --provenance
      - name: Github script for package.json
        uses: actions/github-script@v8
        id: adjust-package
        with:
          script: |
            const script = require('./scripts/adjust-package-json.js');
            const path = './dist/test-lib/package.json';
            const path2 = './dist/test-lib2/package.json';
            const path3 = './dist/test-lib3/package.json';

            const publishConfig = {
              "@boeckmt:registry": "https://npm.pkg.github.com"
            };

            script({github, context}, path, (json)=>{
              json.publishConfig = publishConfig;
              return json;
            });

            script({github, context}, path2, (json)=>{
              json.publishConfig = publishConfig;
              return json;
            });

            script({github, context}, path2, (json)=>{
              json.publishConfig = publishConfig;
              return json;
            });
      - run: |
          for dir in ./dist/*/;
          do
              dir=${dir%*/}

              # Write a minimal .npmrc that contains the token
              cat > "$dir/.npmrc" << EOF
              @boeckmt:registry=https://npm.pkg.github.com
              //npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}
              EOF

              cd "$dir" && npm publish "$dir" --access public --tag "latest"
          done
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}