name: Test setup-node

on:
  push:
    branches:
      - main

jobs:
  node14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: node -v
      - run: npm -v
  node15:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: node -v
      - run: npm -v
  node16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: "@dlr-eoc"
      - run: node -v
      - run: npm -v
      - run: npm i -g npm@6.14.13
      - run: rm -f .npmrc
      - run: npm -v
      - run: npm config list -l
    env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_NPM_TOKEN}}

