name: Test setup-node

on:
  push:
    branches:
      - main

jobs:
  node14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: node -v
      - run: npm -v
  node15:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: node -v
      - run: npm -v
  node16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: node -v
      - run: npm -v
      - run: npm i -g npm@6.14.13
      - run: npm -v
