name: Test Artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: rm -f .npmrc
      - run: npm ci
      - run: npx ng build test-lib --configuration=production
      - name: Github script for package.json
        uses: actions/github-script@v4
        id: adjust-package
        with:
          script: |
            const script = require('./scripts/adjust-package-json.js');
            script({github, context});

      - name: Archive dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "dist"
          path: dist
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download dist result from job build
        uses: actions/download-artifact@v2
        with:
          name: "dist"
          path: dist
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: cd ./dist/test-lib && npm run testexit";
