name: Test Artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: rm -f .npmrc
      - run: npm ci
      - run: npx ng build test-lib --configuration=production
      - name: Archive dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "dist"
          path: dist
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download dist result from job build
        uses: actions/download-artifact@v2
        with:
          name: "dist"
          path: dist
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: find ./dist -mindepth 1 -maxdepth 1 -type d -exec bash -c "cd '{}' && ls -la" \;
      - run: find ./dist -mindepth 1 -maxdepth 1 -type d -exec bash -c "cd '{}' && npm run testexit" \;


