name: Test Artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: rm -f .npmrc
      - run: npm ci
      - run: npx ng build test-lib --configuration=production
      - name: Github script for package.json
        uses: actions/github-script@v4
        id: adjust-package
        with:
          script: |
            const FS = require('fs');
            const path = './dist/test-lib/package.json'
            FS.readFile(path, 'utf8', (error, jsonString) => {
              if (error) {
                console.log(`Error read file ${path}:`, error);
                return;
              }
              try {
                if (jsonString) {
                  const jsonObj: IPackageJSON = JSON.parse(jsonString);
                  jsonObj.scripts = {
                    "testexit": "node --eval \"console.error('ERROR: this should fail the job!!! \\n')\" && exit 1"
                  }
                  const content = jsonObj;
                  FS.writeFile(path, JSON.stringify(content), err => {
                    if (err) {
                      console.log('Error writing file', err);
                    } else {
                      console.log(`Update file ${path}`);
                    }
                  });
                }
              } catch (err) {
                console.log(`Error parsing JSON `, err);
              }
            });

      - name: Archive dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "dist"
          path: dist
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download dist result from job build
        uses: actions/download-artifact@v2
        with:
          name: "dist"
          path: dist
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: find ./dist -mindepth 1 -maxdepth 1 -type d -exec bash -c "cd '{}' && npm run testexit" \;
